DoAnCoSo/DoAnCoSo/Areas/Admin/Controllers/AdminRolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DoAnCoSo.Models;
using Microsoft.AspNetCore.Authorization;

namespace DoAnCoSo.Areas.Admin.Controllers
{
    [Area("Admin")]
    //[Authorize]
    public class AdminRolesController : Controller
    {
        private readonly DataDoAnCoSoContext _context;

        public AdminRolesController(DataDoAnCoSoContext context)
        {
            _context = context;
        }


        //Chức Năng thông báo Start
        protected void SetAlert(string message, string type)
        {
            TempData["AlertMessage"] = message;
            switch (type)
            {
                case "Success":
                    TempData["AlertType"] = "alert-Success"; break;
                case "Warning":
                    TempData["AlertType"] = "alert-Warning"; break;
                case "Error":
                    TempData["AlertType"] = "alert-Error"; break;
                default: TempData["AlertType"] = ""; break;
            }
        }
        //Chức Năng thông báo End

        // GET: Admin/AdminRoles
        public async Task<IActionResult> Index()
        {
            

            return View(await _context.Roles.ToListAsync());
        }

        // GET: Admin/AdminRoles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.RoleId == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // GET: Admin/AdminRoles/Create
        public IActionResult Create()
        {

            return View();
        }

        // POST: Admin/AdminRoles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RoleId,RoleName,DesRole")] Role role)
        {
            if (ModelState.IsValid)
            {
                _context.Add(role);
                await _context.SaveChangesAsync();
                SetAlert("Tạo mới thành công", "Success");                                      // Thông báo cho chức năng
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Admin/AdminRoles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // POST: Admin/AdminRoles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RoleId,RoleName,DesRole")] Role role)
        {
            if (id != role.RoleId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(role);
                    await _context.SaveChangesAsync();
                    SetAlert("Đã Sửa thành công", "Success");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoleExists(role.RoleId))
                    {
                        SetAlert("Sửa sai rầu", "Error");
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Admin/AdminRoles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.RoleId == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // POST: Admin/AdminRoles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var role = await _context.Roles.FindAsync(id);
            if (role != null)
            {
                _context.Roles.Remove(role);
            }

            await _context.SaveChangesAsync();
            SetAlert("Đã xóa thành công", "Success");
            return RedirectToAction(nameof(Index));
        }

        private bool RoleExists(int id)
        {
            return _context.Roles.Any(e => e.RoleId == id);
        }
    }
}

DoAnCoSo/DoAnCoSo/Areas/Admin/Views/AdminRoles/Create.cshtml
@model DoAnCoSo.Models.Role

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>Role</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RoleName" class="control-label"></label>
                <input asp-for="RoleName" class="form-control" />
                <span asp-validation-for="RoleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DesRole" class="control-label"></label>
                <input asp-for="DesRole" class="form-control" />
                <span asp-validation-for="DesRole" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-success"/>
            
                |
           
                <a asp-action="Index" type="button" class="btn btn-outline-info">
                    <i class="uil uil-arrow-circle-left"></i>Back to List
                </a>
            </div>
        </form>
    </div>
</div>

DoAnCoSo/DoAnCoSo/Areas/Admin/Views/AdminRoles/Delete.cshtml
@model DoAnCoSo.Models.Role

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<hr />


<div>
    <h4>Role</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoleName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoleName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DesRole)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DesRole)
        </dd
        

    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="RoleId" type="submit" value="Delete" class="btn btn-danger" />
                |
        <a asp-action="Index" class="btn btn-outline-secondary">Back to List</a>
    </form>
</div>

DoAnCoSo/DoAnCoSo/Areas/Admin/Views/AdminRoles/Details.cshtml
@model DoAnCoSo.Models.Role

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Role</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoleName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoleName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DesRole)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DesRole)
        </dd>
    </dl>
</div>

   @*  <a asp-action="Edit" asp-route-id="@Model?.RoleId" class="btn btn-outline-warning">Edit</a> |
    <a asp-action="Index" class="btn btn-outline-info">Back to List</a> *@


    <div class="page-title-right">
        <div class="btn-group ms-2 d-none d-sm-inline-block">
            <a asp-action="Edit" asp-route-id="@Model?.RoleId" type="button" class="btn btn-outline-warning">
                <i class="uil uil-edit me-1"></i>Edit
            </a>
        </div>
        <div class="btn-group d-none d-sm-inline-block">
            <a asp-action="Index" type="button" class="btn btn-outline-info">
                <i class="uil uil-arrow-circle-left"></i>Back to List
            </a>
        </div>
    </div>

DoAnCoSo/DoAnCoSo/Areas/Admin/Views/AdminRoles/Edit.cshtml
@model DoAnCoSo.Models.Role

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h1 class="mb-3 header-title mt-0">Edit Account</h1>
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="RoleId" />

                    <div class="mb-3">
                        <label asp-for="RoleName" class="form-label" for="exampleInputEmail1">Name Manager/ Staff</label>
                        <input asp-for="RoleName" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Name">
                        <span asp-validation-for="RoleName" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label asp-for="DesRole" class="form-label" for="exampleInputPassword1">Roles</label>
                        <input asp-for="DesRole" type="text" class="form-control" id="exampleInputPassword1" placeholder="Enter Roles">
                        <span asp-validation-for="DesRole" class="text-danger"></span>
                    </div>

                    <div class ="form-group">
                        
                         <input type="submit" value="Save" class="btn btn-outline-success"></input>
                        
                        |
                        <a asp-action="Index" class="btn btn-outline-secondary">Back to List</a>
                    </div>


                </form>
            </div> <!-- end card-body-->
        </div> <!-- end card-->
    </div>
    <!-- end col -->
</div>

DoAnCoSo/DoAnCoSo/Areas/Admin/Views/AdminRoles/Index.cshtml
@model IEnumerable<DoAnCoSo.Models.Role>

@{
    ViewData["Title"] = "Quản lý Quyền Truy Cập";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h1 class="header-title mt-0 mb-1">Quản lý Quyền Truy Cập</h1>
                <p class="sub-header">
                    <div class="mt-2 mt-md-0">
                        <a class="btn btn-danger me-4 mb-2 mb-md-0" asp-action="Create">
                            <i class="uil-plus me-1"></i>Create New
                        </a>
                    </div>
                </p>

                <div class="table-responsive">
                    <table class="table table-hover mb-0">
                        <thead>
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Name</th>
                                <th scope="col">Description Roles</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <th scope="row">@item.RoleId</th>
                                        <td>@item.RoleName</td>
                                        <td>@item.DesRole</td>
                                        <td>
                                            <a class="btn btn-outline-warning" asp-area="Admin" asp-controller="AdminRoles" asp-action="Edit" asp-route-id="@item.RoleId">Edit</a>
                                            <a class="btn btn-outline-primary" asp-area="Admin" asp-controller="AdminRoles" asp-action="Details" asp-route-id="@item.RoleId">View</a>
                                            <a class="btn btn-outline-danger" asp-area="Admin" asp-controller="AdminRoles" asp-action="Delete" asp-route-id="@item.RoleId">Delete</a>

                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>