DoAnCoSo/DoAnCoSo/Areas/Admin/Controllers/AdminAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DoAnCoSo.Models;

namespace DoAnCoSo.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminAccountsController : Controller
    {
        private readonly DataDoAnCoSoContext _context;

        public AdminAccountsController(DataDoAnCoSoContext context)
        {
            _context = context;
        }

        //Chức Năng thông báo Start
        protected void SetAlert(string message, string type)
        {
            TempData["AlertMessage"] = message;
            switch (type)
            {
                case "Success":
                    TempData["AlertType"] = "alert-Success"; break;
                case "Warning":
                    TempData["AlertType"] = "alert-Warning"; break;
                case "Error":
                    TempData["AlertType"] = "alert-Error"; break;
                default: TempData["AlertType"] = ""; break;
            }
        }
        //Chức Năng thông báo End


        // GET: Admin/AdminAccounts
        public async Task<IActionResult> Index()
        {
            ViewData["QuyenTruyCap"] = new SelectList(_context.Roles, "RoleId", "DesRole"); // Chức năng lọc danh sách quyền truy cập

            List<SelectListItem> lsStatus = new List<SelectListItem>();                     // Chức năng trạng thái trong qly tài khoản
            lsStatus.Add(new SelectListItem() { Text = "Active", Value = "1" });
            lsStatus.Add(new SelectListItem() { Text = "Block", Value = "0" });
            ViewData["lsStatus"] = lsStatus;

            var dataDoAnCoSoContext = _context.Accounts.Include(a => a.Role);
            return View(await dataDoAnCoSoContext.ToListAsync());
        }

        // GET: Admin/AdminAccounts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts
                .Include(a => a.Role)
                .FirstOrDefaultAsync(m => m.AccountId == id);
            if (account == null)
            {
                return NotFound();
            }

            return View(account);
        }

        // GET: Admin/AdminAccounts/Create
        public IActionResult Create()
        {
            ViewData["RoleId"] = new SelectList(_context.Roles, "RoleId", "RoleId");
            return View();
        }

        // POST: Admin/AdminAccounts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AccountId,UserNameAcc,Phone,Email,LastLogin,RoleId,PasswordAcc,Active,CreateDate")] Account account)
        {
            if (ModelState.IsValid)
            {
                _context.Add(account);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "RoleId", "RoleId", account.RoleId);
            return View(account);
        }

        // GET: Admin/AdminAccounts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts.FindAsync(id);
            if (account == null)
            {
                return NotFound();
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "RoleId", "RoleId", account.RoleId);
            return View(account);
        }

        // POST: Admin/AdminAccounts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AccountId,UserNameAcc,Phone,Email,LastLogin,RoleId,PasswordAcc,Active,CreateDate")] Account account)
        {
            if (id != account.AccountId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(account);
                    SetAlert("Đã Sửa thành công", "Success");
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AccountExists(account.AccountId))
                    {
                        SetAlert("Sửa sai rầu", "Error");
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "RoleId", "RoleId", account.RoleId);
            return View(account);
        }

        // GET: Admin/AdminAccounts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts
                .Include(a => a.Role)
                .FirstOrDefaultAsync(m => m.AccountId == id);
            if (account == null)
            {
                return NotFound();
            }

            return View(account);
        }

        // POST: Admin/AdminAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var account = await _context.Accounts.FindAsync(id);
            if (account != null)
            {
                _context.Accounts.Remove(account);
            }
            SetAlert("Đã xóa thành công", "Success");
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AccountExists(int id)
        {
            return _context.Accounts.Any(e => e.AccountId == id);
        }
    }
}

DoAnCoSo/DoAnCoSo/Areas/Admin/Views/AdminAccounts/Create.cshtml
@model DoAnCoSo.Models.Account

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>Account</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserNameAcc" class="control-label"></label>
                <input asp-for="UserNameAcc" class="form-control" />
                <span asp-validation-for="UserNameAcc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastLogin" class="control-label"></label>
                <input asp-for="LastLogin" class="form-control" />
                <span asp-validation-for="LastLogin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoleId" class="control-label"></label>
                <select asp-for="RoleId" class ="form-control" asp-items="ViewBag.RoleId"></select>
            </div>
            <div class="form-group">
                <label asp-for="PasswordAcc" class="control-label"></label>
                <input asp-for="PasswordAcc" class="form-control" />
                <span asp-validation-for="PasswordAcc" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CreateDate" class="control-label"></label>
                <input asp-for="CreateDate" class="form-control" />
                <span asp-validation-for="CreateDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DoAnCoSo/DoAnCoSo/Areas/Admin/Views/AdminAccounts/Delete.cshtml
@model DoAnCoSo.Models.Account

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Account</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserNameAcc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserNameAcc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastLogin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastLogin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PasswordAcc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PasswordAcc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Role)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Role.RoleId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="AccountId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DoAnCoSo/DoAnCoSo/Areas/Admin/Views/AdminAccounts/Details.cshtml
@model DoAnCoSo.Models.Account

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Account</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserNameAcc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserNameAcc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastLogin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastLogin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PasswordAcc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PasswordAcc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Role)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Role.RoleId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.AccountId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DoAnCoSo/DoAnCoSo/Areas/Admin/Views/AdminAccounts/Edit.cshtml
@model DoAnCoSo.Models.Account

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit</h1>

<h4>Account</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AccountId" />
            <div class="form-group">
                <label asp-for="UserNameAcc" class="control-label"></label>
                <input asp-for="UserNameAcc" class="form-control" />
                <span asp-validation-for="UserNameAcc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastLogin" class="control-label"></label>
                <input asp-for="LastLogin" class="form-control" />
                <span asp-validation-for="LastLogin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoleId" class="control-label"></label>
                <select asp-for="RoleId" class="form-control" asp-items="ViewBag.RoleId"></select>
                <span asp-validation-for="RoleId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PasswordAcc" class="control-label"></label>
                <input asp-for="PasswordAcc" class="form-control" />
                <span asp-validation-for="PasswordAcc" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CreateDate" class="control-label"></label>
                <input asp-for="CreateDate" class="form-control" />
                <span asp-validation-for="CreateDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>




<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h1 class="header-title mt-0 mb-1">Edit Account</h1>
                

                <form asp-action="Edit" class="parsley-examples">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="AccountId" />

                    <div class="mb-3">
                        <label asp-for="UserNameAcc" class="form-label">Full Name</label>
                        <input asp-for="UserNameAcc" type="text" class="form-control" required placeholder="Full Name " />
                        <span asp-validation-for="UserNameAcc" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label asp-for="Email" class="form-label">E-Mail</label>
                        <input asp-for="Email" type="email" class="form-control" required parsley-type="email" placeholder="Enter a valid e-mail" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label asp-for="Phone" class="form-label">Number</label>
                        <input asp-for="Phone" data-parsley-type="number" type="text" class="form-control" required placeholder="Enter only numbers" />
                        <span asp-validation-for="Phone" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label asp-for="CreateDate" class="col-lg-2 col-form-label" for="example-date">Date</label>
                        <div class="col-lg-10">
                            <input asp-for="CreateDate" class="form-control" id="example-date" type="date" name="date">                            
                        </div>
                        <span asp-validation-for="CreateDate" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label asp-for="LastLogin" class="col-lg-2 col-form-label" for="example-date">LastLogin</label>
                        <div class="col-lg-10">
                            <input asp-for="LastLogin" class="form-control" id="example-date" type="date" name="date">
                        </div>
                        <span asp-validation-for="LastLogin" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label asp-for="RoleId" class="col-lg-2 col-form-label">Role</label>
                        <div class="col-lg-10">
                            <select id="IdRole" name="IdRole" class="form-select" asp-items="ViewBag.QuyenTruyCap">
                                <option value=""></option>
                            </select>
                        </div>
                    </div>

                    <div class="mb-3">
                        <label asp-for="RoleId" class="col-lg-2 col-form-label">Role</label>
                        <div class="col-lg-10">
                            <select id ="IdStatus" name="IdStatus" class="form-select" asp-items="ViewBag.lsStatus">
                                <option value=""></option>
                            </select>
                        </div>
                    </div>

                    <div class="mb-0">
                        <button type="submit" class="btn btn-primary me-1">Submit</button>
                        <button type="reset" class="btn btn-secondary">Cancel</button>
                    </div>
                </form>
            </div>
        </div> <!-- end card -->
    </div> <!-- end col-->-- end col-->
</div>

DoAnCoSo/DoAnCoSo/Areas/Admin/Views/AdminAccounts/Index.cshtml
@model IEnumerable<DoAnCoSo.Models.Account>

@{
    ViewData["Title"] = "Danh Sách Tài Khoản Quản Trị";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

     @* <p>
         <a asp-action="Create">Create New</a>
     </p> *@

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h1 class="header-title mt-0 mb-1">Danh Sách tài khoản</h1>
                <p class="sub-header">
                    <!--
                    <div class="mt-2 mt-md-0">
                        <a class="btn btn-danger me-4 mb-2 mb-md-0" asp-controller="AdminAccounts" asp-action="Create">
                            <i class="uil-plus me-1"></i>Create New
                        </a>
                    </div>
                    -->
                </p>

                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body" style="padding: 20px 50px; height:80px; justify-items:center; ">
                                <div class="row" style="display: flex;">

                                    <div class="col-xl-2 col-sm-4">
                                        <div class="mb-3 mt-3 mt-sm-0">
                                            <select style="min-width: 180px" id="IdRole" name="IdRole" data-plugin="customselect" class="form-select" data-placeholder="Select an option" asp-items="ViewBag.QuyenTruyCap">
                                                <option value="0" disabled selected>Chọn Quyền Truy Cập</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="col-xl-2 col-sm-4">
                                        <div class="mb-3 mt-3 mt-sm-0">
                                            <select id="IdStatus" name="IdStatus" data-plugin="customselect" class="form-select" data-placeholder="Select an option" asp-items="ViewBag.lsStatus">
                                                <option value="" disabled selected>Chọn Trạng Thái</option>
                                            </select>
                                        </div>
                                    </div>

                                </div>
                            </div> <!-- end card-body -->
                        </div> <!-- end card-->
                    </div> <!-- end col -->
                </div>

                <table id="basic-datatable" class="table dt-responsive nowrap w-100">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Full Name</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>Roles</th>
                            <th>Active</th>
                            <th>#</th>
                        </tr>
                    </thead>

                    <tbody>
                        @if (Model != null)
                        {
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.AccountId</td>
                                    <td>@item.UserNameAcc</td>
                                    <td>@item.Email</td>
                                    <td>@item.Phone</td>
                                    <td>@item.Role.DesRole</td>
                                    <td>
                                        @if (item.Active)
                                        {
                                            <div class="spinner-grow text-success m-2" role="status">
                                            </div>
                                            <span class="badge bg-success">Active</span>
                                        }
                                        else
                                        {
                                            <div class="spinner-grow text-danger m-2" role="status">
                                            </div>
                                            <span class="badge bg-danger">Block</span>
                                        }
                                    </td>
                                    <td>
                                        <a class="btn btn-outline-warning" asp-action="Edit" asp-route-id="@item.AccountId">Edit</a> |
                                        <a class="btn btn-outline-primary" asp-action="Details" asp-route-id="@item.AccountId">Details</a> |
                                        <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.AccountId">Delete</a>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div> <!-- end card body-->
        </div> <!-- end card -->
    </div><!-- end col-->
</div>